spring:
  docker:
    compose:
      enabled: true
      skip:
        in-tests: false
      file: "docker-compose.yml"

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

