version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: NaveAnalytics
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NaveAnalytics
    ports:
      - "5432:5432"

